/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author 181720019
 */
public class TelaAdmin2 extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmin2
     */
    public TelaAdmin2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jdpPainel = new javax.swing.JDesktopPane();
        btnAdm_Us = new javax.swing.JButton();
        btnCont_P = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuAdmTrocar = new javax.swing.JMenuItem();
        MenuAdmSair = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jdpPainel.setBackground(new java.awt.Color(255, 255, 255));

        btnAdm_Us.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnAdm_Us.setText("Administração de Usuários");
        btnAdm_Us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdm_UsActionPerformed(evt);
            }
        });

        btnCont_P.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCont_P.setText("Controle de produtos");
        btnCont_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCont_PActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("ADMINISTRADOR");

        jdpPainel.setLayer(btnAdm_Us, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPainel.setLayer(btnCont_P, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpPainel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpPainelLayout = new javax.swing.GroupLayout(jdpPainel);
        jdpPainel.setLayout(jdpPainelLayout);
        jdpPainelLayout.setHorizontalGroup(
            jdpPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPainelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jdpPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCont_P, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdm_Us, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jdpPainelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addGap(50, 410, Short.MAX_VALUE))
        );
        jdpPainelLayout.setVerticalGroup(
            jdpPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPainelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGap(141, 141, 141)
                .addComponent(btnAdm_Us)
                .addGap(45, 45, 45)
                .addComponent(btnCont_P)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicial");

        MenuAdmTrocar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MenuAdmTrocar.setText("Trocar de  usuário");
        MenuAdmTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdmTrocarActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAdmTrocar);

        MenuAdmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuAdmSair.setText("Sair");
        MenuAdmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdmSairActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAdmSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdm_UsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdm_UsActionPerformed
        TelaUsuarios_adm tela = new TelaUsuarios_adm();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdm_UsActionPerformed

    private void btnCont_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCont_PActionPerformed
        TelaProdutos tela = new TelaProdutos();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCont_PActionPerformed

    private void MenuAdmTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdmTrocarActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuAdmTrocarActionPerformed

    private void MenuAdmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdmSairActionPerformed
        
    }//GEN-LAST:event_MenuAdmSairActionPerformed
 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAdmSair;
    private javax.swing.JMenuItem MenuAdmTrocar;
    private javax.swing.JButton btnAdm_Us;
    private javax.swing.JButton btnCont_P;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpPainel;
    // End of variables declaration//GEN-END:variables
}
